name: riot-os-ide # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: IDE and toolchain to develop RIOT OS applications # 79 char long summary
description: |
  An IDE which contains all the necessary dependencies to develop applications
  for RIOT OS. Includes an emulation to provide a dev environment.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mono:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://download.mono-project.com/sources/mono/mono-6.12.0.90.tar.xz
    source-type: tar
    install-via: prefix
    build-packages:
      - cmake
  vscodium:
    plugin: nil
    stage-snaps:
      - codium/latest/stable
  renode:
    plugin: nil
    source: https://github.com/renode/renode/releases/download/v1.11.0/renode-1.11.0.linux-portable.tar.gz
    source-type: tar
    build-attributes: [keep-execstack]
    override-build: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc/renode
      cp $SNAPCRAFT_PART_BUILD/renode_bundled $SNAPCRAFT_PART_INSTALL/bin/
      cp -r $SNAPCRAFT_PART_BUILD/platforms $SNAPCRAFT_PART_INSTALL/etc/renode/
      cp -r $SNAPCRAFT_PART_BUILD/scripts $SNAPCRAFT_PART_INSTALL/etc/renode/
      cp $SNAPCRAFT_PART_BUILD/.renode-root $SNAPCRAFT_PART_INSTALL/etc/renode/
    after:
      - mono

apps:
  renode:
    command: bin/renode_bundled
  mono:
    command: bin/mono
    